version: '2'

services:

  bitcoin-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: bitcoin-base-testnet

  counterparty-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterparty-base-testnet
    links:
      - bitcoin-testnet

  mongodb:
    extends:
      file: docker-compose.tmpl.yml
      service: mongodb-base

  redis:
    extends:
      file: docker-compose.tmpl.yml
      service: redis-base


  armory-utxsvr-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: armory-utxsvr-base-testnet
    links:
      - bitcoin-testnet


  counterblock-testnet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterblock-base-testnet
    links:
      - bitcoin-testnet
      - counterparty-testnet
      - mongodb
      - redis
      - armory-utxsvr-testnet

  counterwallet:
    extends:
      file: docker-compose.tmpl.yml
      service: counterwallet-base
    links:
      - redis
      - counterblock-testnet

volumes:
  bitcoin-data:
  counterparty-data:
  counterblock-data:
  mongodb-data:
  armory-data:
